apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: PLACEHOLDER_AWS_REGION
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: challenge-meli-api-secrets
  namespace: challenge-meli
  labels:
    app.kubernetes.io/name: challenge-meli-api
    app.kubernetes.io/part-of: challenge-meli
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: challenge-meli-api-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: challenge-meli-api
  dataFrom:
    - extract:
        key: PLACEHOLDER_AWS_SECRET_PATH
