apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: challenge-meli-api
  namespace: challenge-meli
  labels:
    app.kubernetes.io/name: challenge-meli-api
    app.kubernetes.io/part-of: challenge-meli
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: challenge-meli-api
  minReplicas: 3
  maxReplicas: 80
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 4
          periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
